- hosts: centos2
  become: true
  roles:
  - apache
  - mysql
# Standaloe task
  tasks:
   - name: install script with db connectivity
     copy:
       src: db.php
       dest: "{{ apache_document_root_path }}db.php"
       mode: 0755
