- hosts: centos1
  vars:
    writers:
      - Tolstoy
      - Dostoyevski
      - London
      - Sabahattin
      - Austen
  tasks:
  - name: Template loop example
    template:
      src: template.j2
      dest: /tmp/output.txt
